[project]
name = "application_settings"
version = "0.6.0.dev"
description = "For providing a python application with configuration and/or settings"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Stockwatchdevs", email = "stockwatchdevs@gmail.com" }]
keywords = ["configuration", "settings", "dataclass", "pydantic", "toml", "json"]
dynamic = ["classifiers"]
requires-python = ">=3.10"
dependencies = [
  "loguru (>=0.7.0)",
  "pathvalidate (>=2.5)",
  "pydantic (>=2.0)",
  "tomlkit (>=0.12)",
  "attributes-doc (>=0.3.0)",
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]

[project.urls]
homepage = "https://github.com/StockwatchDev/application_settings"
repository = "https://github.com/StockwatchDev/application_settings"
documentation = "https://stockwatchdev.github.io/application_settings/stable/"
changelog = "https://stockwatchdev.github.io/application_settings/stable/CHANGELOG/"

[tool.poetry]
include = [
  { path = "CHANGELOG.md", format = "sdist" },
  { path = "LICENSE", format = "sdist" },
  { path = "README.md", format = "sdist" },
  { path = "tests", format = "sdist" },
  { path = "examples", format = "sdist" },
]

[tool.poetry.dependencies]
typing-extensions = { version = ">=4.5.0", python = "<3.12" }

[tool.poetry.group.testing]
optional = true

[tool.poetry.group.testing.dependencies]
pytest = ">=7.0"
pytest-cov = ">=4.0"

[tool.poetry.group.typing]
optional = true

[tool.poetry.group.typing.dependencies]
mypy = ">=1.1"
lxml = ">=4.9"

[tool.poetry.group.style]
optional = true

[tool.poetry.group.style.dependencies]
black = ">=22.10"
isort = ">=5.12"
pylint = ">=3.3"

[tool.poetry.group.testrunner]
optional = true

[tool.poetry.group.testrunner.dependencies]
tox = ">=4.4"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
black = ">=22.10"
mkdocs = ">=1.5"
mkdocstrings-python = ">=1.5"
mkdocs-material = ">=9.2"
pymdown-extensions = ">=10.1"
mkdocs-include-markdown-plugin = ">=6.0"
mkdocs-gen-files = ">=0.5"
mkdocs-literate-nav = ">=0.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
  # omit these folders
  # "*/config_sections/*",
  # omit these single files
  "__main__.py",
  "config.py",
  "main.py",
]
branch = true

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_also = [
  # Don't complain about missing debug-only code:
  "def __repr__",
  "if self\\.debug",

  # Don't complain if tests don't hit defensive assertion code:
  "raise AssertionError",
  "raise NotImplementedError",

  # Don't complain if non-runnable code isn't run:
  "if 0:",
  "if __name__ == .__main__.:",

  # Don't complain about abstract methods, they aren't run:
  "@(abc\\.)?abstractmethod",
]

ignore_errors = true

[tool.pytest.ini_options]
addopts = "--cov-report=xml:coverage.xml --cov-report=term-missing --cov-config=pyproject.toml --cov=application_settings --cov=tests"
testpaths = ["tests"]
filterwarnings = ["error"]

[tool.black]
target-version = ["py311", "py312", "py313", "py314"]

[tool.isort]
profile = "black"

[tool.mypy]
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true
show_error_codes = true
show_error_context = true
ignore_missing_imports = true

[tool.pylint.main]
load-plugins = [
  "pylint.extensions.bad_builtin",
  "pylint.extensions.code_style",
  "pylint.extensions.typing",
  "pylint.extensions.no_self_use",
]

[tool.pylint.messages_control]
# Reasons disabled:
# format - handled by black
# wrong-import-order - isort guards this
# fixme - too handy for now
# consider-alternative-union-syntax: we still support 3.9
disable = ["fixme", "format", "wrong-import-order", "consider-alternative-union-syntax"]
enable = ["useless-suppression", "use-symbolic-message-instead"]

[tool.pylint.typecheck]
mixin-class-rgx = ".*[Mm]ix[Ii]n"

[tool.pylint.typing]
runtime-typing = false

[tool.pylint.similarities]
ignore-imports = "yes"

[tool.tox]
requires = ["tox>=4.49"]

# Generates: py310-pytest, py310-mypy, py311-pytest, py311-mypy, ... py314-mypy
env_list = [{ product = [["py310", "py311", "py312", "py313", "py314"], ["pytest", "typing"]] }, "style", "docs"]

[tool.tox.env_run_base]
description = "Run {env_name}"
skip_missing_interpreters = true

# Let Poetry handle the dependencies and installation of the environment
skip_install = true
allowlist_externals = ["poetry"]

commands_pre = [
  { replace = "if", condition = "factor.pytest", then = [
    [
      "poetry",
      "install",
      "--with",
      "testing",
      "-v",
    ],
  ], extend = true },
  { replace = "if", condition = "factor.typing", then = [
    [
      "poetry",
      "install",
      "--with",
      "typing",
      "-v",
    ],
  ], extend = true },
]

commands = [
  { replace = "if", condition = "factor.pytest", then = [
    [
      "poetry",
      "run",
      "pytest",
    ],
  ], extend = true },
  { replace = "if", condition = "factor.typing", then = [
    [
      "poetry",
      "run",
      "mypy",
      "{posargs:src}",
    ],
  ], extend = true },
]

[tool.tox.env.style]
description = "Run style checks"
skip_install = true
allowlist_externals = ["poetry"]
commands_pre = [["poetry", "install", "--with", "style", "-v"]]
commands = [
  [
    "poetry",
    "run",
    "black",
    "--check",
    "{posargs:src}",
  ],
  [
    "poetry",
    "run",
    "isort",
    "--check",
    "--diff",
    "{posargs:src}",
  ],
  [
    "poetry",
    "run",
    "pylint",
    "{posargs:src}",
  ],
]

[tool.tox.env.docs]
description = "Generate documentation"
skip_install = true
allowlist_externals = ["poetry"]
commands_pre = [["poetry", "install", "--with", "docs", "-v"]]
commands = [["poetry", "run", "mkdocs", "build", "-f", "./docs/mkdocs.yml", "-d", "../site"]]
